version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev